INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('SUNDAY', 'POP', 0.25);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('MONDAY', 'POP', 0.07);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('TUESDAY', 'POP', 0.06);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('WEDNESDAY', 'POP', 0.02);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('THURSDAY', 'POP', 0.1);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('FRIDAY', 'POP', 0.15);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('SATURDAY', 'POP', 0.2);

INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('SUNDAY', 'MPB', 0.3);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('MONDAY', 'MPB', 0.5);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('TUESDAY', 'MPB', 0.1);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('WEDNESDAY', 'MPB', 0.15);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('THURSDAY', 'MPB', 0.2);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('FRIDAY', 'MPB', 0.25);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('SATURDAY', 'MPB', 0.3);

INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('SUNDAY', 'CLASSIC', 0.35);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('MONDAY', 'CLASSIC', 0.3);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('TUESDAY', 'CLASSIC', 0.5);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('WEDNESDAY', 'CLASSIC', 0.8);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('THURSDAY', 'CLASSIC', 0.13);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('FRIDAY', 'CLASSIC', 0.18);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('SATURDAY', 'CLASSIC', 0.25);

INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('SUNDAY', 'ROCK', 0.4);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('MONDAY', 'ROCK', 0.1);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('TUESDAY', 'ROCK', 0.15);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('WEDNESDAY', 'ROCK', 0.15);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('THURSDAY', 'ROCK', 0.15);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('FRIDAY', 'ROCK', 0.2);
INSERT INTO CASHBACK_PERCENTAGE (DAY_OF_WEEK, GENRE, PERCENTAGE_VALUE) VALUES ('SATURDAY', 'ROCK', 0.4);