CREATE TABLE IF NOT EXISTS ALBUM (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(200) NOT NULL,
    ARTIST VARCHAR(200) NOT NULL,
    GENRE VARCHAR(7) NOT NULL,
    PRICE DECIMAL(8, 2) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CASHBACK_PERCENTAGE (
    ID INT NOT NULL AUTO_INCREMENT,
    GENRE VARCHAR(7) NOT NULL,
    DAY_OF_WEEK VARCHAR(9) NOT NULL,
    PERCENTAGE_VALUE DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SALE (
    ID INT NOT NULL AUTO_INCREMENT,
    DATE_SOLD DATE NOT NULL,
    TOTAL_CASHBACK_VALUE DECIMAL(12, 2) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SALE_ITEM (
    ID INT NOT NULL AUTO_INCREMENT,
    CASHBACK_VALUE DECIMAL(8, 2) NOT NULL,
    ALBUM_ID INT NOT NULL,
    SALE_ID INT NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE SALE_ITEM ADD FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ID);
ALTER TABLE SALE_ITEM ADD FOREIGN KEY (SALE_ID) REFERENCES SALE(ID);